### PR TITLE
PostgreSQL connection, Production/Development launch options and corresponding connection strings in hidden appsettings

### PR DESCRIPTION
**Pull request by Ladam0203**
I have set up a basic DbContext, I passed the connection strings for the development and production database server to it and tried to connect, which was succesful. The server runs on my Raspberry Pi.

I also set up a production and development launch setting, and specified the connection strings in the appsettings.Development.json and appsetting.Production.json. So the server will connect to the corresponding database based on the launch options. I also left in Swagger for the development launch option. 

As the appsettings*.json files are part of the .gitignore, these have to be shared somewhere else, not to expose the connection string.

And I'll stop working ahead, I just wanted to make sure that PostgreSQL will surely work :D

### CODE REVIEW

**Comment by Ladam0203** [comment]
I think you gotta mark your comment as an approve comment somehow, then merge with Rebase and Merge.

**Comment by RomanMeasv** [comment]
*confused as fuk* so you cant push without us reviewing the code first? you can’t approve it yourself? i just wrote something cuz you might want to see the things on git, right? idek😵‍💫😵‍💫

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Ladam0203** [comment]
Nah, this is how it is set up, you can only merge into main or dev with opening a PR, and having someone else review it first. Based on Bent's teaching :D I think it's also nice bc it's relatively easier to track progress and having someone go over you code gives us an extra safety net.

**Comment by RomanMeasv** [comment]
Ye I get the point but just for now I simply wrote approved just so you can have it on git - do you need me to approve all the commits or we go through them some other time?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by StAl3x — APPROVED** [review]
Aint much to say about this one, from my side

**Pull request merged**
